apiVersion: v1
kind: Service
metadata:
  name: flask-datetime-service
spec:
  type: NodePort
  selector:
    app: flask-datetime
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
